# Generated by Django 2.2.4 on 2019-08-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='spaceClass',
            fields=[
                ('flight_number', models.IntegerField(primary_key=True, serialize=False)),
                ('mission_name', models.CharField(max_length=100)),
                ('rocket_name', models.CharField(max_length=100)),
                ('mission_patch', models.CharField(max_length=100, null=True)),
                ('time', models.DateTimeField(null=True)),
            ],
        ),
    ]
